# Generated by Django 5.0.6 on 2024-05-23 01:23

import django.core.validators
import solicitudes.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50, validators=[solicitudes.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=50, validators=[solicitudes.validators.validate_only_letters])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro'), ('N', 'No informado')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('dni', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(999999999)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['creation_date'],
            },
        ),
    ]
